### ISSUE TITLE
Is it based on Kyty? 

### ISSUE THREAD

**Issue by GamingDucking** [SysRay/psOff_public#5]
I am just wondering if is it based on Kyty or completely something else? (because It reminded me of Kyty based on the screenshots)

**Comment by SysRay** [comment]
It's something else/new, written from scratch and specs.
I originally wanted to contribute to KYTY, but no comments and writing every std function as an own custom function kept me away + it’s sadly inactive.

Regarding the title, since my amd overlay doesn't want to pick the emulator up and display fps etc., I just included it in the title.

**Comment by GamingDucking** [comment]
I see.
